; Need to finish gchart-pie
(defvar sas-graph-help
  '(
    ("gchart" (
	       ("block" "Creates block charts in which the height of the blocks represents the value of the chart statistic for each category of data")
	       ("hbar" "Creates horizontal area bar charts where each bar shows two dimensions (a width variable and response variable) for each category variable.")
	       ("hbar3d" "Creates 3d-horizontal area bar charts where each bar shows two dimensions (a width variable and response variable) for each category variable.")
	       ("vbar" "Creates vertical area bar charts where each bar shows two dimensions (a width variable and response variable) for each category variable.")
	       ("vbar3d" "Creates vertical area bar charts where each bar shows two dimensions (a width variable and response variable) for each category variable.")
	       ("pie" "Create pie charts in which the size of a pie slice represents the value of the chart statistic for that category of data in relation to the total chart statistic for all categories.")
	       ("pie3d" "Create 3d pie charts in which the size of a pie slice represents the value of the chart statistic for that category of data in relation to the total chart statistic for all categories.")
	       ("donut" "Create donut charts in which the size of a pie slice represents the value of the chart statistic for that category of data in relation to the total chart statistic for all categories.")
	       ("star" "Creates star charts in which the length of the spines represents the value of the chart statistic for each category of data or midpoint")
	       ))
    ("garebar" (
		("hbar" "Creates horizontal area bar charts where each bar shows two dimensions (a width variable and response variable) for each category variable.")
		("hbar3d" "Creates 3d-horizontal area bar charts where each bar shows two dimensions (a width variable and response variable) for each category variable.")
		("vbar" "Creates vertical area bar charts where each bar shows two dimensions (a width variable and response variable) for each category variable.")
		("vbar3d" "Creates vertical area bar charts where each bar shows two dimensions (a width variable and response variable) for each category variable.")
		))
    ("gbarline" (
		 ("bar" "Creates vertical bar charts in which the height of the bars represents the value of the bar statistic for each category of data.")
		 ("plot" "Creates a plot overlay on top of the bar line chart")
		 ))
    )
  )
;;
;; The following precodes specify what type of completion to do on the option like data= "(data)" will
;; complete the data step.  
;;
;; No completion is assumed when  there is nothing in the ().
;; Anything that has a list of choices seperated by | is assuemd to complete those choices.
;; If you wish to put an additional completion based on a function enclose it in [].
;;
;; (catalog) 		= Complete Catalog
;; (data) 		= Complete Data
;; (output-data) 	= Complete Output Data
;; (file) 		= Fileref or name completion (include '' & directory inclusion?)
;; (library) 		= Library/libref.
;; (format) 		= Format completion
;; (color) 		= Color completion
;; (font) 		= Font Specification
;; (pattern) 		= Fill pattern
;;
;; Not completed, but may be completed in the future.
;;
;; (ods) 		= ODS document/destination
;; (axis-expression)  	= Axis expression
;; (variable) 		= Variable Name
;; (linetype) 		= Line Type
;;
;; Not completed (with no intention to complete)
;;
;; (#) 				= Specifies a number
;; (%) 				= Specifies a percent.
;; (password) 			= Specifies password.
;; (translation-list) 		= Specifies a translation between the two character sets.
;; (out-graphics-catalog) 	= Specifies a graphics catalog.
(defvar sas-graph-options
  '(
    ("ganno" (
	      ("annotate=" "(data) Specifies a data set that includes Annotate variables that identify graphics commands and parameters.")
;	      ("anno=" "(Annotate-data-set) Specifies a data set that includes Annotate variables that identify graphics commands and parameters.")
	      ("datasys" "Indicates that absolute or relative data-dependent coordinates occur in the Annotate data set and scales the coordinates to fit the graphics output area.")
	      ("description='/**/'" "Specifies the description of the catalog entry for the chart. The maximum length is 256 characters")
;	      ("des='/**/'" "Specifies the description of the catalog entry for the chart. The maximum length is 256 characters")
	      ("gout=" "(gout) Specifies the SAS catalog in which to save the graphics output produced by the GANNO procedure")
	      ("imagemap=" "(output-data) Creates a temporary SAS data set that is used to generate an image map in an HTML output file")
	      ("name=" "('/**/'|variable-name) Specifies (1) name of the catalog entry for the graph (''), or (2) A variable name for each value for which a separate graph is produced.")
	      ))
    ("gareabar" (
		 ("data=" "(data) Contains the data to be graphed")
		 ))
    ("garebar.vbar" (
		    ("cframe=" "(color) Specifies a background color for the chart.")
		    ("ctext=" "(color) Specifies a color for all text on the chart.")
		    ("discrete" "Causes the chart to show discrete width role values on the width axis rather than a continuous axis.")
		    ("frame" "Draws a frame around the procedure output area. The frame color is the first color in the colors list.")
		    ("noframe" "Suppresses the frame that is drawn around the chart by default.")
		    ("name=" "When DEV=ACTXIMG, specifies the name of the graph (PNG file) produced by GAREABAR.")
		    ("subgroup=" " Used to subdivide the response-variable dimension (SUMVAR).")
		    ("wstat=" "(sum|pct|percent) Specifies whether the width variable is represented as a percentage or as a sum.")
		    ("rstat=" "(sum|pct|percent) Specifies whether the subgrouping (if SUBGROUP is specified) variable is represented as a percentage or as a sum.")
		    ))
    ("garebar.hbar" (
		    ("cframe=" "(color) Specifies a background color for the chart.")
		    ("ctext=" "(color) Specifies a color for all text on the chart.")
		    ("discrete" "Causes the chart to show discrete width role values on the width axis rather than a continuous axis.")
		    ("frame" "Draws a frame around the procedure output area. The frame color is the first color in the colors list.")
		    ("noframe" "Suppresses the frame that is drawn around the chart by default.")
		    ("name=" "When DEV=ACTXIMG, specifies the name of the graph (PNG file) produced by GAREABAR.")
		    ("subgroup=" " Used to subdivide the response-variable dimension (SUMVAR).")
		    ("wstat=" "(sum|pct|percent) Specifies whether the width variable is represented as a percentage or as a sum.")
		    ("rstat=" "(sum|pct|percent) Specifies whether the subgrouping (if SUBGROUP is specified) variable is represented as a percentage or as a sum.")
		    ))
    ("garebar.vbar3d" (
		    ("cframe=" "(color) Specifies a background color for the chart.")
		    ("ctext=" "(color) Specifies a color for all text on the chart.")
		    ("discrete" "Causes the chart to show discrete width role values on the width axis rather than a continuous axis.")
		    ("frame" "Draws a frame around the procedure output area. The frame color is the first color in the colors list.")
		    ("noframe" "Suppresses the frame that is drawn around the chart by default.")
		    ("name=" "When DEV=ACTXIMG, specifies the name of the graph (PNG file) produced by GAREABAR.")
		    ("subgroup=" " Used to subdivide the response-variable dimension (SUMVAR).")
		    ("wstat=" "(sum|pct|percent) Specifies whether the width variable is represented as a percentage or as a sum.")
		    ("rstat=" "(sum|pct|percent) Specifies whether the subgrouping (if SUBGROUP is specified) variable is represented as a percentage or as a sum.")
		    ))
    ("garebar.hbar3d" (
		    ("cframe=" "(color) Specifies a background color for the chart.")
		    ("ctext=" "(color) Specifies a color for all text on the chart.")
		    ("discrete" "Causes the chart to show discrete width role values on the width axis rather than a continuous axis.")
		    ("frame" "Draws a frame around the procedure output area. The frame color is the first color in the colors list.")
		    ("noframe" "Suppresses the frame that is drawn around the chart by default.")
		    ("name=" "When DEV=ACTXIMG, specifies the name of the graph (PNG file) produced by GAREABAR.")
		    ("subgroup=" " Used to subdivide the response-variable dimension (SUMVAR).")
		    ("wstat=" "(sum|pct|percent) Specifies whether the width variable is represented as a percentage or as a sum.")
		    ("rstat=" "(sum|pct|percent) Specifies whether the subgrouping (if SUBGROUP is specified) variable is represented as a percentage or as a sum.")
		    ))
    ("gbarline" (
	      ("annotate=" "(data) Specifies a data set that includes Annotate variables that identify graphics commands and parameters.")
;	      ("anno=" "(Annotate-data-set) Specifies a data set that includes Annotate variables that identify graphics commands and parameters.")
	      ("imagemap=" "(output-data) Creates a temporary SAS data set that is used to generate an image map in an HTML output file")
	      ("data=" "(data) Contains the data to be graphed")
	      ))
    ("gbarline.bar" (
; Graph Options
		     ("annotate=" "(data) Annotate-data-set")
		     ("cautoref=" "(color) Reference-line-color")
		     ("caxis=" "(color) axis-color")
		     ("cerror=" "(color Error-bar-color")
		     ("cframe=" "(color) Background-color")
		     ("coutline=" "([color]|same) Bar-outline-color")
		     ("cref=" "(color) Reference line color(s)")
		     ("ctext=" "(color) Text-color")
		     ("frame" "Draws a frame around the procedure output area. The frame color is the first color in the colors list.")
		     ("noframe" "Suppresses the frame that is drawn around the chart by default.")
		     ("frontref" "specifies that reference lines drawn by the AUTOREF or REF= options should be drawn in front of the bars.")
		     ("lautoref=" "(#) specifies a line type for reference lines drawn at major tick marks (number).")
		     ("lref=" "(#) specifies a line type for reference lines drawn (number).")
		     ("patternid=" "(by|midpoint) Specifies the way fill patterns are assigned. BY changes patterns each time the value of the BY variable changes. All bars use the same pattern if the GBARLINE procedure does not include a BY statement, MIDPOINT changes patterns every time the midpoint value changes.")
		     ("space=" "(#) Specifies the amount of space between individual bars.")
		     ("width=" "(#) Specifies the width of the bars.")
		     ("woutline=" "(#) Bar-outline-width")
; Statistics options
		     ("cfreq" "Displays cumulative frequency above the bars")
		     ("clm=" "Specifies the confidence intervals to use when drawing error bars")
		     ("cpercent" "Displays the cumulative percentage statistic above the bars")
		     ("errorbars=" "(bars|both|top)Error bars; BARS draws error bars as bars half the width of the main bars. BOTH draws error bars as two ticks joined by a line. TOP draws the error bar as a tick for the upper confidence limit that is joined to the top of the bar by a line.")
		     ("freq" "Displays the frequency statistic above the bars")
		     ("freq=" "(#) specifies a variable whose values weight the contribution of each observation in the computation of the bar statistic.")
		     ("inside=" "(freq|cfreq|percent|cpercent|pct|cpct|sum|mean) Displays the values of the specified statistic inside the bars.")
		     ("mean" "Displays the mean statistic above the bars")
		     ("outside=" "(freq|cfreq|percent|cpercent|pct|cpct|sum|mean) Displays the values of the specified statistic outside the bars.")
		     ("percent" "Displays the percentages of observations having a given value for the bar variable above the bars")
		     ("sum" "Displays the sum statistic above the bars")
		     ("sumvar=" "(var) Summary Variable")
		     ("type=" "(freq|cfreq|percent|pct|cpercent|cpct|sum|mean) If the SUMVAR= option is not used, statistic can be one of the following: (FREQ,CFREQ,PCT,CPCT).  Otherwise SUM and Mean can be used.")
;; Midpoint options
		     ("discrete" "Treats a numeric bar variable as a discrete variable rather than as a continuous variable")
		     ("levels=" "(#) Specifies the number of midpoints for a numeric bar variable.")
		     ("midpoints=" "(old|[#])Specifies the midpoint values for the bars. If midpoints=old uses old Nelder algorithm to calculate midpoints")
		     ("missing" "accepts a missing value as a valid midpoint for the bar variable.")
		     ("range" "Displays on the axis of the chart the range of numeric values represented by each bar")
;; Axes options
		     ("ascending" "Arranges the bars in ascending order of the value of the bar statistic")
		     ("autoref" "Draws a reference line at each major tick mark on the chart (left) response axis")
		     ("axis=" "Specifies values for the major tick mark divisions on the response axis or assigns the specified AXIS definition to the axis")
		     ("raxis=" "Specifies values for the major tick mark divisions on the response axis or assigns the specified AXIS definition to the axis")
		     ("clipref" "Clips the reference lines at the bars.")
		     ("descending" "Arranges the bars in descending order of the value of the bar statistic")
		     ("maxis=" "Assigns the specified AXIS definition to the midpoint axis")
		     ("minor=" "(#) Number of minor tick marks") 
		     ("noaxis" "Suppress all axes.")
		     ("nobaseref" "Suppresses the zero reference line when the SUM or MEAN bar statistic has negative values.")
		     ("nozero" "Suppresses any midpoints for which there are no corresponding values of the bar variable and, hence, no bar")
		     ("range" "Displays on the axis of the chart the range of numeric values represented by each bar")
		     ("ref=" "Draws reference lines at the specified points on the bar response axis")
; Catalog entry description options
		     ("description='/**/'" "Specifies the description of the catalog entry for the chart")
		     ("name='/**/'" "Specifies the name of the catalog entry for the graph.")
; ODS
		     ("html=" "Identifies the variable in the input data set whose values create links in the HTML file created by the ODS statement.")
		     ))
    ("gbarline.plot" (
; Appearance options:
		      ("noline" "Suppresses the drawing of the line plot overlay, regardless of what is specified in the SYMBOL statement.")
		      ("nomarker" "Suppresses the drawing of the marker symbol, regardless of what is specified in the SYMBOL statement.")
; statistic options:
		      ("cfreq" "Prints the cumulative frequency.")
		      ("cpercent" "Prints the cumulative percentages.")	
		      ("freq" "Prints the frequency of each bar to the side of the chart.")
		      ("freq=" "(variable) Specifies a data set variable that represents a frequency count for each observation.")
		      ("mean" "Prints the mean of the observations represented by each bar.")
		      ("percent" "Prints the percentages of observations having a given value for the chart variable.")
		      ("sum" "Prints the sum of observations having a given value for the chart variable.")
		      ("sumvar=" "(var) Summary Variable")
		      ("type=" "(freq|cfreq|percent|pct|cpercent|cpct|sum|mean) If the SUMVAR= option is not used, statistic can be one of the following: (FREQ,CFREQ,PCT,CPCT).  Otherwise SUM and Mean can be used.")
; Axes options:
		      ("ascending" "Arranges the bars in ascending order of the value of the bar statistic")
		      ("axis=" "Specifies values for the major tick mark divisions on the response axis or assigns the specified AXIS definition to the axis")
		      ("descending" "Arranges the bars in descending order of the value of the bar statistic")
		      ("raxis=" "Specifies values for the major tick mark divisions on the response axis or assigns the specified AXIS definition to the axis")
		      ("minor=" "(#) Number of minor tick marks") 
; HTML
		      ("html=" "Identifies the variable in the input data set whose values create links in the HTML file created by the ODS statement.")
		      ))
    ("gchart" (
	      ("annotate=" "(data) Specifies a data set that includes Annotate variables that identify graphics commands and parameters.")
;	      ("anno=" "(Annotate-data-set) Specifies a data set that includes Annotate variables that identify graphics commands and parameters.")
	      ("gout=" "(gout) Specifies the SAS catalog in which to save the graphics output produced by the GANNO procedure")
	      ("imagemap=" "(output-data) Creates a temporary SAS data set that is used to generate an image map in an HTML output file")
	      ("name=" "('/**/'|variable-name) Specifies (1) name of the catalog entry for the graph (''), or (2) A variable name for each value for which a separate graph is produced.")
	      ))
    ("gchart.hbar3d" (
; Graph Options
		     ("annotate=" "(data) Annotate-data-set")
		     ("cautoref=" "(color) Reference-line-color")
		     ("caxis=" "(color) axis-color")
		     ("cerror=" "(color Error-bar-color")
		     ("cframe=" "(color) Background-color")
		     ("coutline=" "([color]|same) Bar-outline-color")
		     ("cref=" "(color) Reference line color(s)")
		     ("ctext=" "(color) Text-color")
		     ("frame" "Draws a frame around the procedure output area. The frame color is the first color in the colors list.")
		     ("noframe" "Suppresses the frame that is drawn around the chart by default.")
		     ("lautoref=" "(#) specifies a line type for reference lines drawn at major tick marks (number).")
		     ("lref=" "(#) specifies a line type for reference lines drawn (number).")
		     ("patternid=" "(by|group|midpoint|subgroup) Specifies the way fill patterns are assigned. BY changes patterns each time the value of the BY variable changes. All bars use the same pattern if the GBARLINE procedure does not include a BY statement, MIDPOINT changes patterns every time the midpoint value changes.")
		     ("space=" "(#) Specifies the amount of space between individual bars.")
		     ("width=" "(#) Specifies the width of the bars.")
		     ("woutline=" "(#) Bar-outline-width")
		     ("gspace=" "(#) Group spacing")
		     ("iframe=" "Identifies the image file you wish to fill the backplane frame of your three-dimensional bar charts")
		     ("legend=" "Assigns the specified LEGEND definition to the legend generated by the SUBGROUP= option")
		     ("nolegend" "No legend")
		     ("cfreq" "Displays cumulative frequency above the bars")
		     ("clm=" "Specifies the confidence intervals to use when drawing error bars")
		     ("cpercent" "Displays the cumulative percentage statistic above the bars")
		     ("errorbars=" "(bars|both|top)Error bars; BARS draws error bars as bars half the width of the main bars. BOTH draws error bars as two ticks joined by a line. TOP draws the error bar as a tick for the upper confidence limit that is joined to the top of the bar by a line.")
		     ("freq" "Displays the frequency statistic above the bars")
		     ("g100" "Calculates the percentage and cumulative percentage statistics separately for each group")
		     ("inside=" "(freq|cfreq|percent|cpercent|pct|cpct|sum|mean) Displays the values of the specified statistic inside the bars.")
		     ("mean" "Displays the mean statistic above the bars")
		     ("outside=" "(freq|cfreq|percent|cpercent|pct|cpct|sum|mean) Displays the values of the specified statistic outside the bars.")
		     ("percent" "Displays the percentages of observations having a given value for the bar variable above the bars")
		     ("sum" "Displays the sum statistic above the bars")
		     ("sumvar=" "(var) Summary Variable")
		     ("type=" "(freq|cfreq|percent|pct|cpercent|cpct|sum|mean) If the SUMVAR= option is not used, statistic can be one of the following: (FREQ,CFREQ,PCT,CPCT).  Otherwise SUM and Mean can be used.")
		     ("discrete" "Treats a numeric bar variable as a discrete variable rather than as a continuous variable")
		     ("group=" "(var) Organizes the data according to the values of group-variable")
		     ("levels=" "(#) Specifies the number of midpoints for a numeric bar variable.")
		     ("midpoints=" "(old|[#])Specifies the midpoint values for the bars. If midpoints=old uses old Nelder algorithm to calculate midpoints")
		     ("missing" "accepts a missing value as a valid midpoint for the bar variable.")
		     ("subgroup=" " Used to subdivide the response-variable dimension (SUMVAR).")
		     ("ascending" "Arranges the bars in ascending order of the value of the bar statistic")
		     ("autoref" "Draws a reference line at each major tick mark on the chart (left) response axis")
		     ("axis=" "Specifies values for the major tick mark divisions on the response axis or assigns the specified AXIS definition to the axis")
		     ("clipref" "Clips the reference lines at the bars.")
		     ("descending" "Arranges the bars in descending order of the value of the bar statistic")
		     ("maxis=" "Assigns the specified AXIS definition to the midpoint axis")
		     ("gaxis=" "assigns the specified AXIS definition to the group axis")
		     ("noaxis" "Suppress all axes.")
		     ("description='/**/'" "Specifies the description of the catalog entry for the chart. The maximum length is 256 characters")
		     ("name='/**/'" "(var) Specifies (1) name of the catalog entry for the graph (''), or (2) A variable name for each value for which a separate graph is produced.")
		     ("html=" "Identifies the variable in the input data set whose values create links in the HTML file created by the ODS statement.")
		     ("legend=" "Assigns the specified LEGEND definition to the legend generated by the SUBGROUP= option")
		     ("html_legend=" "(var) Identifies the variable in the input data set whose values create links in the HTML file that is created by the ODS statement")
		     ("frontref" "Specifies that reference lines drawn by the AUTOREF or REF= options should be drawn in front of the bars")
		     ("cfreqlabel=" "Specifies the text of the column label for the CFREQ statistic in the table of statistics")
		     ("sumlabel=" "Specifies the text of the column label for the SUM statistic in the table of statistics")
		     ("percentlabel=" "Specifies the text of the column label for the Percent statistic in the table of statistics")
		     ("freqlabel=" "Specifies the text of the column label for the FREQ statistic in the table of statistics")
		     ("cpercentlabel=" "Specifies the text of the column label for the CPERCENT statistic in the table of statistics")
		     ("imagestyle=" "(tile|fit) Option for three-dimensional bar charts, specifies whether to use multiple instances of an image to fill the backplane frame (TILE) or to stretch a single instance of an image to fill the backplane frame (FIT)")
		     ("shape" " Hbar3d and vbar3d only")
		     ))
    ("gchart.vbar3d" (
; Graph Options
		     ("annotate=" "(data) Annotate-data-set")
		     ("cautoref=" "(color) Reference-line-color")
		     ("caxis=" "(color) axis-color")
		     ("cerror=" "(color Error-bar-color")
		     ("cframe=" "(color) Background-color")
		     ("coutline=" "([color]|same) Bar-outline-color")
		     ("cref=" "(color) Reference line color(s)")
		     ("ctext=" "(color) Text-color")
		     ("frame" "Draws a frame around the procedure output area. The frame color is the first color in the colors list.")
		     ("noframe" "Suppresses the frame that is drawn around the chart by default.")
		     ("lautoref=" "(#) specifies a line type for reference lines drawn at major tick marks (number).")
		     ("lref=" "(#) specifies a line type for reference lines drawn (number).")
		     ("patternid=" "(by|group|midpoint|subgroup) Specifies the way fill patterns are assigned. BY changes patterns each time the value of the BY variable changes. All bars use the same pattern if the GBARLINE procedure does not include a BY statement, MIDPOINT changes patterns every time the midpoint value changes.")
		     ("space=" "(#) Specifies the amount of space between individual bars.")
		     ("width=" "(#) Specifies the width of the bars.")
		     ("woutline=" "(#) Bar-outline-width")
		     ("gspace=" "(#) Group spacing")
		     ("iframe=" "Identifies the image file you wish to fill the backplane frame of your three-dimensional bar charts")
		     ("legend=" "Assigns the specified LEGEND definition to the legend generated by the SUBGROUP= option")
		     ("nolegend" "No legend")
		     ("cfreq" "Displays cumulative frequency above the bars")
		     ("clm=" "Specifies the confidence intervals to use when drawing error bars")
		     ("cpercent" "Displays the cumulative percentage statistic above the bars")
		     ("errorbars=" "(bars|both|top)Error bars; BARS draws error bars as bars half the width of the main bars. BOTH draws error bars as two ticks joined by a line. TOP draws the error bar as a tick for the upper confidence limit that is joined to the top of the bar by a line.")
		     ("freq" "Displays the frequency statistic above the bars")
		     ("g100" "Calculates the percentage and cumulative percentage statistics separately for each group")
		     ("inside=" "(freq|cfreq|percent|cpercent|pct|cpct|sum|mean) Displays the values of the specified statistic inside the bars.")
		     ("mean" "Displays the mean statistic above the bars")
		     ("outside=" "(freq|cfreq|percent|cpercent|pct|cpct|sum|mean) Displays the values of the specified statistic outside the bars.")
		     ("percent" "Displays the percentages of observations having a given value for the bar variable above the bars")
		     ("sum" "Displays the sum statistic above the bars")
		     ("sumvar=" "(var) Summary Variable")
		     ("type=" "(freq|cfreq|percent|pct|cpercent|cpct|sum|mean) If the SUMVAR= option is not used, statistic can be one of the following: (FREQ,CFREQ,PCT,CPCT).  Otherwise SUM and Mean can be used.")
		     ("discrete" "Treats a numeric bar variable as a discrete variable rather than as a continuous variable")
		     ("group=" "(var) Organizes the data according to the values of group-variable")
		     ("levels=" "(#) Specifies the number of midpoints for a numeric bar variable.")
		     ("midpoints=" "(old|[#])Specifies the midpoint values for the bars. If midpoints=old uses old Nelder algorithm to calculate midpoints")
		     ("missing" "accepts a missing value as a valid midpoint for the bar variable.")
		     ("subgroup=" " Used to subdivide the response-variable dimension (SUMVAR).")
		     ("ascending" "Arranges the bars in ascending order of the value of the bar statistic")
		     ("autoref" "Draws a reference line at each major tick mark on the chart (left) response axis")
		     ("axis=" "Specifies values for the major tick mark divisions on the response axis or assigns the specified AXIS definition to the axis")
		     ("clipref" "Clips the reference lines at the bars.")
		     ("descending" "Arranges the bars in descending order of the value of the bar statistic")
		     ("maxis=" "Assigns the specified AXIS definition to the midpoint axis")
		     ("gaxis=" "assigns the specified AXIS definition to the group axis")
		     ("noaxis" "Suppress all axes.")
		     ("description='/**/'" "Specifies the description of the catalog entry for the chart. The maximum length is 256 characters")
		     ("name='/**/'" "(var) Specifies (1) name of the catalog entry for the graph (''), or (2) A variable name for each value for which a separate graph is produced.")
		     ("html=" "Identifies the variable in the input data set whose values create links in the HTML file created by the ODS statement.")
		     ("legend=" "Assigns the specified LEGEND definition to the legend generated by the SUBGROUP= option")
		     ("html_legend=" "(var) Identifies the variable in the input data set whose values create links in the HTML file that is created by the ODS statement")
		     ("frontref" "Specifies that reference lines drawn by the AUTOREF or REF= options should be drawn in front of the bars")
		     ("cfreqlabel=" "Specifies the text of the column label for the CFREQ statistic in the table of statistics")
		     ("sumlabel=" "Specifies the text of the column label for the SUM statistic in the table of statistics")
		     ("percentlabel=" "Specifies the text of the column label for the Percent statistic in the table of statistics")
		     ("freqlabel=" "Specifies the text of the column label for the FREQ statistic in the table of statistics")
		     ("cpercentlabel=" "Specifies the text of the column label for the CPERCENT statistic in the table of statistics")
		     ("imagestyle=" "(tile|fit) Option for three-dimensional bar charts, specifies whether to use multiple instances of an image to fill the backplane frame (TILE) or to stretch a single instance of an image to fill the backplane frame (FIT)")
		     ("shape" " Hbar3d and vbar3d only")
		     ))
    ("gchart.vbar" (
; Graph Options
		     ("annotate=" "(data) Annotate-data-set")
		     ("cautoref=" "(color) Reference-line-color")
		     ("caxis=" "(color) axis-color")
		     ("cerror=" "(color Error-bar-color")
		     ("cframe=" "(color) Background-color")
		     ("coutline=" "([color]|same) Bar-outline-color")
		     ("cref=" "(color) Reference line color(s)")
		     ("ctext=" "(color) Text-color")
		     ("frame" "Draws a frame around the procedure output area. The frame color is the first color in the colors list.")
		     ("noframe" "Suppresses the frame that is drawn around the chart by default.")
		     ("lautoref=" "(#) specifies a line type for reference lines drawn at major tick marks (number).")
		     ("lref=" "(#) specifies a line type for reference lines drawn (number).")
		     ("patternid=" "(by|group|midpoint|subgroup) Specifies the way fill patterns are assigned. BY changes patterns each time the value of the BY variable changes. All bars use the same pattern if the GBARLINE procedure does not include a BY statement, MIDPOINT changes patterns every time the midpoint value changes.")
		     ("space=" "(#) Specifies the amount of space between individual bars.")
		     ("width=" "(#) Specifies the width of the bars.")
		     ("woutline=" "(#) Bar-outline-width")
		     ("gspace=" "(#) Group spacing")
		     ("iframe=" "Identifies the image file you wish to fill the backplane frame of your three-dimensional bar charts")
		     ("legend=" "Assigns the specified LEGEND definition to the legend generated by the SUBGROUP= option")
		     ("nolegend" "No legend")
		     ("cfreq" "Displays cumulative frequency above the bars")
		     ("clm=" "Specifies the confidence intervals to use when drawing error bars")
		     ("cpercent" "Displays the cumulative percentage statistic above the bars")
		     ("errorbars=" "(bars|both|top)Error bars; BARS draws error bars as bars half the width of the main bars. BOTH draws error bars as two ticks joined by a line. TOP draws the error bar as a tick for the upper confidence limit that is joined to the top of the bar by a line.")
		     ("freq" "Displays the frequency statistic above the bars")
		     ("g100" "Calculates the percentage and cumulative percentage statistics separately for each group")
		     ("inside=" "(freq|cfreq|percent|cpercent|pct|cpct|sum|mean) Displays the values of the specified statistic inside the bars.")
		     ("mean" "Displays the mean statistic above the bars")
		     ("outside=" "(freq|cfreq|percent|cpercent|pct|cpct|sum|mean) Displays the values of the specified statistic outside the bars.")
		     ("percent" "Displays the percentages of observations having a given value for the bar variable above the bars")
		     ("sum" "Displays the sum statistic above the bars")
		     ("sumvar=" "(var) Summary Variable")
		     ("type=" "(freq|cfreq|percent|pct|cpercent|cpct|sum|mean) If the SUMVAR= option is not used, statistic can be one of the following: (FREQ,CFREQ,PCT,CPCT).  Otherwise SUM and Mean can be used.")
		     ("discrete" "Treats a numeric bar variable as a discrete variable rather than as a continuous variable")
		     ("group=" "(var) Organizes the data according to the values of group-variable")
		     ("levels=" "(#) Specifies the number of midpoints for a numeric bar variable.")
		     ("midpoints=" "(old|[#])Specifies the midpoint values for the bars. If midpoints=old uses old Nelder algorithm to calculate midpoints")
		     ("missing" "accepts a missing value as a valid midpoint for the bar variable.")
		     ("subgroup=" " Used to subdivide the response-variable dimension (SUMVAR).")
		     ("ascending" "Arranges the bars in ascending order of the value of the bar statistic")
		     ("autoref" "Draws a reference line at each major tick mark on the chart (left) response axis")
		     ("axis=" "Specifies values for the major tick mark divisions on the response axis or assigns the specified AXIS definition to the axis")
		     ("clipref" "Clips the reference lines at the bars.")
		     ("descending" "Arranges the bars in descending order of the value of the bar statistic")
		     ("maxis=" "Assigns the specified AXIS definition to the midpoint axis")
		     ("gaxis=" "assigns the specified AXIS definition to the group axis")
		     ("noaxis" "Suppress all axes.")
		     ("description='/**/'" "Specifies the description of the catalog entry for the chart. The maximum length is 256 characters")
		     ("name='/**/'" "(var) Specifies (1) name of the catalog entry for the graph (''), or (2) A variable name for each value for which a separate graph is produced.")
		     ("html=" "Identifies the variable in the input data set whose values create links in the HTML file created by the ODS statement.")
		     ("legend=" "Assigns the specified LEGEND definition to the legend generated by the SUBGROUP= option")
		     ("html_legend=" "(var) Identifies the variable in the input data set whose values create links in the HTML file that is created by the ODS statement")
;		     ("frontref" "Specifies that reference lines drawn by the AUTOREF or REF= options should be drawn in front of the bars")
;		     ("cfreqlabel=" "Specifies the text of the column label for the CFREQ statistic in the table of statistics")
;		     ("sumlabel=" "Specifies the text of the column label for the SUM statistic in the table of statistics")
;		     ("percentlabel=" "Specifies the text of the column label for the Percent statistic in the table of statistics")
;		     ("freqlabel=" "Specifies the text of the column label for the FREQ statistic in the table of statistics")
;		     ("cpercentlabel=" "Specifies the text of the column label for the CPERCENT statistic in the table of statistics")
;		     ("imagestyle=" "(tile|fit) Option for three-dimensional bar charts, specifies whether to use multiple instances of an image to fill the backplane frame (TILE) or to stretch a single instance of an image to fill the backplane frame (FIT)")
;		     ("shape" " Hbar3d and vbar3d only")
		     ))
    ("gchart.hbar" (
; Graph Options
		     ("annotate=" "(data) Annotate-data-set")
		     ("cautoref=" "(color) Reference-line-color")
		     ("caxis=" "(color) axis-color")
		     ("cerror=" "(color Error-bar-color")
		     ("cframe=" "(color) Background-color")
		     ("coutline=" "([color]|same) Bar-outline-color")
		     ("cref=" "(color) Reference line color(s)")
		     ("ctext=" "(color) Text-color")
		     ("frame" "Draws a frame around the procedure output area. The frame color is the first color in the colors list.")
		     ("noframe" "Suppresses the frame that is drawn around the chart by default.")
		     ("lautoref=" "(#) specifies a line type for reference lines drawn at major tick marks (number).")
		     ("lref=" "(#) specifies a line type for reference lines drawn (number).")
		     ("patternid=" "(by|group|midpoint|subgroup) Specifies the way fill patterns are assigned. BY changes patterns each time the value of the BY variable changes. All bars use the same pattern if the GBARLINE procedure does not include a BY statement, MIDPOINT changes patterns every time the midpoint value changes.")
		     ("space=" "(#) Specifies the amount of space between individual bars.")
		     ("width=" "(#) Specifies the width of the bars.")
		     ("woutline=" "(#) Bar-outline-width")
		     ("gspace=" "(#) Group spacing")
		     ("iframe=" "Identifies the image file you wish to fill the backplane frame of your three-dimensional bar charts")
		     ("legend=" "Assigns the specified LEGEND definition to the legend generated by the SUBGROUP= option")
		     ("nolegend" "No legend")
		     ("cfreq" "Displays cumulative frequency above the bars")
		     ("clm=" "Specifies the confidence intervals to use when drawing error bars")
		     ("cpercent" "Displays the cumulative percentage statistic above the bars")
		     ("errorbars=" "(bars|both|top)Error bars; BARS draws error bars as bars half the width of the main bars. BOTH draws error bars as two ticks joined by a line. TOP draws the error bar as a tick for the upper confidence limit that is joined to the top of the bar by a line.")
		     ("freq" "Displays the frequency statistic above the bars")
		     ("g100" "Calculates the percentage and cumulative percentage statistics separately for each group")
		     ("inside=" "(freq|cfreq|percent|cpercent|pct|cpct|sum|mean) Displays the values of the specified statistic inside the bars.")
		     ("mean" "Displays the mean statistic above the bars")
		     ("outside=" "(freq|cfreq|percent|cpercent|pct|cpct|sum|mean) Displays the values of the specified statistic outside the bars.")
		     ("percent" "Displays the percentages of observations having a given value for the bar variable above the bars")
		     ("sum" "Displays the sum statistic above the bars")
		     ("sumvar=" "(var) Summary Variable")
		     ("type=" "(freq|cfreq|percent|pct|cpercent|cpct|sum|mean) If the SUMVAR= option is not used, statistic can be one of the following: (FREQ,CFREQ,PCT,CPCT).  Otherwise SUM and Mean can be used.")
		     ("discrete" "Treats a numeric bar variable as a discrete variable rather than as a continuous variable")
		     ("group=" "(var) Organizes the data according to the values of group-variable")
		     ("levels=" "(#) Specifies the number of midpoints for a numeric bar variable.")
		     ("midpoints=" "(old|[#])Specifies the midpoint values for the bars. If midpoints=old uses old Nelder algorithm to calculate midpoints")
		     ("missing" "accepts a missing value as a valid midpoint for the bar variable.")
		     ("subgroup=" " Used to subdivide the response-variable dimension (SUMVAR).")
		     ("ascending" "Arranges the bars in ascending order of the value of the bar statistic")
		     ("autoref" "Draws a reference line at each major tick mark on the chart (left) response axis")
		     ("axis=" "Specifies values for the major tick mark divisions on the response axis or assigns the specified AXIS definition to the axis")
		     ("clipref" "Clips the reference lines at the bars.")
		     ("descending" "Arranges the bars in descending order of the value of the bar statistic")
		     ("maxis=" "Assigns the specified AXIS definition to the midpoint axis")
		     ("gaxis=" "assigns the specified AXIS definition to the group axis")
		     ("noaxis" "Suppress all axes.")
		     ("description='/**/'" "Specifies the description of the catalog entry for the chart. The maximum length is 256 characters")
		     ("name='/**/'" "(var) Specifies (1) name of the catalog entry for the graph (''), or (2) A variable name for each value for which a separate graph is produced.")
		     ("html=" "Identifies the variable in the input data set whose values create links in the HTML file created by the ODS statement.")
		     ("legend=" "Assigns the specified LEGEND definition to the legend generated by the SUBGROUP= option")
		     ("html_legend=" "(var) Identifies the variable in the input data set whose values create links in the HTML file that is created by the ODS statement")
;		     ("frontref" "Specifies that reference lines drawn by the AUTOREF or REF= options should be drawn in front of the bars")
;		     ("cfreqlabel=" "Specifies the text of the column label for the CFREQ statistic in the table of statistics")
;		     ("sumlabel=" "Specifies the text of the column label for the SUM statistic in the table of statistics")
;		     ("percentlabel=" "Specifies the text of the column label for the Percent statistic in the table of statistics")
;		     ("freqlabel=" "Specifies the text of the column label for the FREQ statistic in the table of statistics")
;		     ("cpercentlabel=" "Specifies the text of the column label for the CPERCENT statistic in the table of statistics")
;		     ("imagestyle=" "(tile|fit) Option for three-dimensional bar charts, specifies whether to use multiple instances of an image to fill the backplane frame (TILE) or to stretch a single instance of an image to fill the backplane frame (FIT)")
;		     ("shape" " Hbar3d and vbar3d only")
		     ))
    ("gchart.block" (
		     ("annotate=" "(data) Specifies a data set that includes Annotate variables that identify graphics commands and parameters.")
		     ("caxis=" "(color) axis-color")
		     ("coutline=" "([color]|same) Bar-outline-color")
		     ("ctext=" "(color) Specifies a color for all text on the chart.")
		     ("noheading" "No heading")
		     ("nolegend" "No heading")
		     ("patternid=" "(by|group|midpoint|subgroup) Specifies the way fill patterns are assigned. BY changes patterns each time the value of the BY variable changes. All bars use the same pattern if the GBARLINE procedure does not include a BY statement, MIDPOINT changes patterns every time the midpoint value changes.")
		     ("woutline=" "(#) Bar-outline-width")
		     
		     ("discrete" "Causes the chart to show discrete width role values on the width axis rather than a continuous axis.")
		     ("levels=" "(#) Specifies the number of midpoints for a numeric bar variable.")
		     ("midpoints=" "(old|[#])Specifies the midpoint values for the bars. If midpoints=old uses old Nelder algorithm to calculate midpoints")
		     ("missing" "accepts a missing value as a valid midpoint for the bar variable.")
		     ("subgroup=" " Used to subdivide the response-variable dimension (SUMVAR).")
		     ("freq=" "(#) specifies a variable whose values weight the contribution of each observation in the computation of the bar statistic.")
		     ("sumvar=" "(var) Summary Variable")
		     ("type=" "(freq|cfreq|percent|pct|cpercent|cpct|sum|mean) If the SUMVAR= option is not used, statistic can be one of the following: (FREQ,CFREQ,PCT,CPCT).  Otherwise SUM and Mean can be used.")
		     ("description='/**/'" "Specifies the description of the catalog entry for the chart. The maximum length is 256 characters")
		     ("name='/**/'" "(var) Specifies (1) name of the catalog entry for the graph (''), or (2) A variable name for each value for which a separate graph is produced.")
		     ("html=" "Identifies the variable in the input data set whose values create links in the HTML file created by the ODS statement.")
		     ("legend=" "Assigns the specified LEGEND definition to the legend generated by the SUBGROUP= option")
		     ("html_legend=" "(var) Identifies the variable in the input data set whose values create links in the HTML file that is created by the ODS statement")
		     ("blockmax=" "Specifies the chart statistic value of the tallest block on the chart.  Allows production of series of block charts using the same scale.")
		     ("group=" "(var) Organizes the data according to the values of group-variable")
		     ("g100" "Calculates the percentage and cumulative percentage statistics separately for each group")
		     ))
; need to finish gchart.pie
    ("gchart.pie" (
		   ("annotate=" "(data) Specifies a data set that includes Annotate variables that identify graphics commands and parameters.")
		   ("cfill=" "(color) Fill Color")
		   ("coutline=" "([color],same) Slice color outline")
		   ("detail_radius=" "(%) Percent that determines the size of the detail pie")
		   ("explode=" "Value list")
		   ("fill=" "(solid|x) specifies the fill pattern for all slices in the chart: SOLID rotates a solid fill through the colors list as many times as necessary. X rotates a single hatch pattern through the colors list as many times as necessary")
		   ("invisible=" "Makes the specified slices invisible, as if they had been removed from the pie")
		   ("noheading" "No heading")
		   ("woutline=" "(#) Slice outline width")
		   ("freq=" "(#) specifies a variable whose values weight the contribution of each observation in the computation of the bar statistic.")
		   ("sumvar=" "(var) Summary Variable")
		   ("type=" "(freq|percent|pct|cpercent|cpct|sum|mean) If the SUMVAR= option is not used, statistic can be one of the following: (FREQ,CFREQ,PCT,CPCT).  Otherwise SUM and Mean can be used.")
		   ))
    )
  )


(defvar sas-graph-procs
  '(
("proc ganno annotate=
	   description=
	   gout=
	   imagemap=
	   name=;
run;" 0)
("proc gareabar data=; 
    vbar /;
    vbar3d /; 
    hbar /; 
    hbar3d /;
run;" 0)
("proc gbarline data=
	      annotate=
	      imagemap=;
    bar /;
    plot /;
run;" 0)
)
"Alist of sas procs tags for use with lightning completion"
)

(provide 'sasmod-cookies-graph)